apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../workloads

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: banik123/argocd-demo
  newTag: b16dd578f88a8ca31863b78ca95d83b0d759b51b
