apiVersion: v1
kind: Service
metadata:
  name: MI-service
  labels:
    app: machineinfo
  name: machineinfo
  
spec:
  selector: 
    app: machineinfo
  type: NodePort  # use LoadBalancer as type here
  ports:
    - Port: 9000
      targetPort: 9000
      nodePort - 31000
