apiVersion: v1
kind: Service
metadata:
  name: MI-service
  labels:
    app: machineinfo
  name: machineinfo
  
spec:
  selector: 
    app: machineinfo
  type: NodePort  # use LoadBalancer as type here
  ports:
    - nodePort: 31000
      Port: 9000
      targetPort: 9000
      
