apiVersion: v1
kind: Service
metadata:
  name: MI-service
  labels:
    app: machineinfo
  name: machineinfo
  
spec:
  selector: 
    app: machineinfo
  type: LoadBalancer  # use LoadBalancer as type here
  ports:
    - port: 9000
      targetPort: 9000
      
